### ISSUE TITLE
multiple-feature gp representation

### ISSUE THREAD

**Issue by lacava** [lacava/few#12]
incorporate a multi-output program representation for which each individual has its own ML model.

**Comment by Ohjeah** [comment]
You may want to have a look at the [MultiOutputRegressor](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html).

**Comment by lacava** [comment]
this is handled in a separate project i've been working on called Feat; https://github.com/lacava/feat
