### ISSUE TITLE
If original features are found by FEW, transform() method fails with TypeError

### ISSUE THREAD

**Issue by jay-reynolds** [lacava/few#34]
If original features are found by FEW, transform() method fails with TypeError

eg:

>>> print('Model: {}'.format(learner.print_model()))

Model: original features

>>> Phi = learner.transform(X_test.values)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-fa52fbd107f8> in <module>()
----> 1 Phi = learner.transform(X_test.values)

~/anaconda3/envs/ml/lib/python3.6/site-packages/FEW-0.0.38-py3.6-macosx-10.7-x86_64.egg/few/few.py in transform(self, x, inds, labels)
    395             # return np.asarray(Parallel(n_jobs=10)(delayed(self.out)(I,x,labels,self.otype) for I in self._best_inds)).transpose()
    396             return np.asarray(
--> 397                 [self.out(I,x,labels,self.otype) for I in self._best_inds]).transpose()
    398 
    399 

TypeError: 'NoneType' object is not iterable

**Comment by lacava** [comment]
looks like you're using an old version of FEW (0.0.38). (Did that get installed when you ran `pip install few`? It shouldn't.) The latest version is 0.0.46 (0.0.48 on github), and fixes this issue.

**Comment by jay-reynolds** [comment]
You're right.  Not sure how I managed that.  
I built & installed it from source from this repo (or so I thought) using:
 CC=gcc-7 python setup.py install

Investigating...

**Comment by jay-reynolds** [comment]
Ok, I must've been doing too many things at once yesterday.
Started fresh.

few version is now 0.0.48
Thank you again for the help!
