### ISSUE TITLE
feat vs few?

### ISSUE THREAD

**Issue by echo66** [lacava/few#35]
Greetings!

I would like to know if there is any practical difference between the two projects. I'm asking this because testing feat would require a lot more effort than few and, as such, I need to know if it is worth it.

Thanks in advance!

**Comment by lacava** [comment]
Thanks for your interest! We'll be releasing a preprint that describes [Feat](https://github.com/lacava/feat) in the coming days. The basic differences are

- Feat optimizes a population of models; Few optimizes one 
- Feat supports multi-type features in one model; Few does single type
- Feat has gradient descent built in, we haven't added that to Few yet 

Feat is definitely harder to install and we haven't made an official release yet, so you might want to start with Few and go from there. I'll keep this thread updated once we get some tangible empirical comparisons between the two.

**Comment by echo66** [comment]
Gradient descent??? I'm probably a "little bit" behind the state of the art regarding evolutionary approaches but...doesn't gradient descent require your function to be differentiable? Evolutionary approaches are not required to be differentiable, right?

**Comment by lacava** [comment]
Feat will learn the constants for the subset of features that are differentiable using gradient descent. It is a local search built within the larger search for feature forms.

**Comment by echo66** [comment]
Hey @lacava !

Really interesting idea! Thanks or the explanation!

**Comment by lacava** [comment]
here is the [arxiv preprint](https://arxiv.org/abs/1807.00981) I mentioned.
